# Generated by Django 5.1.6 on 2025-03-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='Payment_ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(blank=True, db_column='Payment_Method', max_length=11, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=7, null=True)),
                ('order', models.OneToOneField(blank=True, db_column='Order_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
