# Generated by Django 5.1.6 on 2025-03-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('feedback_id', models.AutoField(db_column='Feedback_ID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', null=True)),
                ('feedback_date', models.DateField(auto_now_add=True, db_column='Feedback_Date')),
                ('customer', models.ForeignKey(blank=True, db_column='Customer_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('order', models.ForeignKey(blank=True, db_column='Order_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'db_table': 'customer_feedback',
            },
        ),
    ]
