# Generated by Django 5.1.6 on 2025-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_Number', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['name'],
            },
        ),
    ]
