# Generated by Django 5.1.6 on 2025-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(db_column='Restaurant_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, db_column='Zip_Code', max_length=10, null=True)),
                ('contact_no', models.CharField(db_column='Contact_No', max_length=15, unique=True)),
                ('branch_type', models.CharField(choices=[('Main', 'Main'), ('Branch', 'Branch')], default='Main', max_length=10)),
                ('branch_name', models.CharField(default='Headquarters', max_length=100)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
