# Generated by Django 5.1.6 on 2025-03-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='Order_ID', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(db_column='Total_Amount', decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True, db_column='Order_Date')),
                ('customer', models.ForeignKey(blank=True, db_column='Customer_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('restaurant', models.ForeignKey(blank=True, db_column='Restaurant_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('special_requests', models.TextField(blank=True, db_column='Special_Requests', null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menu')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
            options={
                'db_table': 'Order_Details',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quantity_greater_than_0')],
                'unique_together': {('order', 'menu')},
            },
        ),
    ]
